# Generated by Django 3.0.5 on 2020-08-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='Названия статьи')),
                ('content', models.TextField(max_length=150, verbose_name='Описание статьи')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликована?')),
                ('data_published', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Стаья',
                'verbose_name_plural': 'Cтатьи',
            },
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
